In [38]:
import plotly.express as px
import pandas as pd
import numpy as np

In [39]:
df = pd.read_csv("../results/sc-runs/gmmtests-synth.csv")
df

     Missingness  Replicate  n_components
0            0.1          0             2
1            0.1          1             2
2            0.1          2             2
3            0.1          3             2
4            0.1          4             2
..           ...        ...           ...
445          0.5         45             1
446          0.5         46             1
447          0.5         47             1
448          0.5         48             1
449          0.5         49             1

[450 rows x 3 columns]

In [40]:
piv = df.pivot(index="Missingness", columns="Replicate", values="n_components")
piv

Replicate,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
Missingness,,,,,,,,,,,,,,,,,,,,,
0.10,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
0.15,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
0.20,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
0.25,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
0.30,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
0.35,1,1,2,1,1,1,1,1,2,1,...,1,1,1,1,1,1,1,1,1,2
0.40,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
0.45,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
0.50,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [54]:
counts = piv.agg(pd.Series.value_counts, axis=1).reset_index().melt(["Missingness"], var_name="No. of GMM components", value_name="Amount of replicates").fillna(0)
counts["Missingness"] = counts["Missingness"].apply(lambda x: x*100)
counts

    Missingness No. of GMM components  Amount of replicates
0          10.0                     1                   0.0
1          15.0                     1                   0.0
2          20.0                     1                   0.0
3          25.0                     1                   0.0
4          30.0                     1                   0.0
5          35.0                     1                  40.0
6          40.0                     1                  50.0
7          45.0                     1                  50.0
8          50.0                     1                  50.0
9          10.0                     2                  50.0
10         15.0                     2                  50.0
11         20.0                     2                  50.0
12         25.0                     2                  50.0
13         30.0                     2                  50.0
14         35.0                     2                  10.0
15         40.0                     2                   0.0
16         45.0                     2                   0.0
17         50.0                     2                   0.0

In [58]:
fig = px.bar(
    counts,
    x="Missingness",
    y="Amount of replicates",
    color="No. of GMM components"
)

fig.update_layout(width=800, height=400)
fig.update_xaxes(tickmode='array', tickvals=counts["Missingness"], title="Missingness in %")
fig.show()