In [26]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

## Cluster only (slow dist algos)

In [27]:
res_mesquita_eed = ["EED", 43.766, 11.019, 4.818, 31.741, 30.933]
res_esdmvn = ["ESD/MVN", 29.982, 0.347, 0.290, 28.607, 28.393]
res_esdgmm = ["ESD/GMM", 39.713, 5.003, 4.855, 33.705, 33.038]

df = pd.DataFrame(
    columns=["Method", "Total", "dist_rows", "gmm_rows", "dist_cols", "gmm_cols"],
    data=[res_mesquita_eed, res_esdgmm, res_esdmvn]
)

df["Other"] = df["Total"] - df["dist_rows"] - df["dist_cols"]
df["dist_est_rows"] = df["dist_rows"] - df["gmm_rows"]
df["dist_est_cols"] = df["dist_cols"] - df["gmm_cols"]

df

,Method,Total,dist_rows,gmm_rows,dist_cols,gmm_cols,Other,dist_est_rows,dist_est_cols
0,EED,43.766,11.019,4.818,31.741,30.933,1.006,6.201,0.808
1,ESD/GMM,39.713,5.003,4.855,33.705,33.038,1.005,0.148,0.667
2,ESD/MVN,29.982,0.347,0.290,28.607,28.393,1.028,0.057,0.214

In [28]:
fig = go.Figure()

fig.add_trace(go.Bar(
    y=df["Method"],
    x=df["Other"],
    orientation="h",
    name="Other",
    marker=dict(
        color="#616161"
    )
))

# fig.add_trace(go.Bar(
#     y=df["Method"],
#     x=df["gmm_rows"],
#     orientation="h",
#     name="GMMMissing (rows)"
# ))
# fig.add_trace(go.Bar(
#     y=df["Method"],
#     x=df["dist_est_rows"],
#     orientation="h",
#     name="Distance Estimation (rows)"
# ))

# fig.add_trace(go.Bar(
#     y=df["Method"],
#     x=df["gmm_cols"],
#     orientation="h",
#     name="GMMMissing (cols)"
# ))
# fig.add_trace(go.Bar(
#     y=df["Method"],
#     x=df["dist_est_cols"],
#     orientation="h",
#     name="Distance Estimation (cols)"
# ))

fig.add_trace(go.Bar(
    y=df["Method"],
    x=df["gmm_cols"] + df["gmm_rows"],
    orientation="h",
    name="GMMMissing"
))

fig.add_trace(go.Bar(
    y=df["Method"],
    x=df["dist_est_rows"] + df["dist_est_cols"],
    orientation="h",
    name="Distance Estimation"
))

fig.update_layout(
    # barmode="stack",
    width=800,
    height=400,

)

fig.update_xaxes(
    title="Execution time (s)"
)

fig.show()

## Visu runtime

In [29]:
cols = ["Dataset", "Builder constructor", "add_heatmap", "add_col_dendrogram", "add_row_dendrogram", "add_col_group_markers", "get_figure", "Figure.show"]
vals_aml = ["AML", 0.052, 0.033, 0.025, 0.171, 0.004, 0.012, 0.363]
vals_ev = ["EV", 0.06, 0.063, 0.023, 1.092, 0.005, 0.010, 0.781]

visu_df = pd.DataFrame(columns=cols, data=[vals_aml, vals_ev])
visu_df.set_index("Dataset", inplace=True)
visu_df.columns.name = "Function"
visu_df = visu_df.T
visu_df.reset_index(inplace=True)
visu_df

Dataset               Function    AML     EV
0          Builder constructor  0.052  0.060
1                  add_heatmap  0.033  0.063
2           add_col_dendrogram  0.025  0.023
3           add_row_dendrogram  0.171  1.092
4        add_col_group_markers  0.004  0.005
5                   get_figure  0.012  0.010
6                  Figure.show  0.363  0.781

In [30]:
fig = go.Figure()

fig.add_trace(go.Bar(
    y=visu_df["Function"],
    x=visu_df["AML"],
    orientation="h",
    name="AML"
))

fig.add_trace(go.Bar(
    y=visu_df["Function"],
    x=visu_df["EV"],
    orientation="h",
    name="EV"
))

fig.update_layout(
    # barmode="stack",
    width=800,
    height=500,

)

fig.update_xaxes(
    title="Execution time (s)"
)
fig.update_yaxes(
    title="Code segment"
)

fig.update_layout(
    legend=dict(
        title=dict(
            text="Dataset"
        )
    )
)

fig.show()